version: '3.8'

services:
  backend:
    build:
      context: ./roman-numeral-backend
    ports:
      - "8080:8080"
    depends_on:
      - jaeger

  frontend:
    build:
      context: ./roman-numeral-ui
    ports:
      - "5173:5173"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Collector HTTP (backend)
      - "4318:4318"    # OTLP HTTP (frontend)
